---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3
  attributes:
    mongodb:
      data_dir: '/data'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mongodb_cloudmanager::install]
      - recipe[mongodb_cloudmanager::configure]
    attributes:
